on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: run build
        run: |
          npm i
          npm run build:prod
          cd example
          npm i
          npm run build:prod
          mv bundled.html dist/index.html
            - name: Upload a Build Artifact

            
      - name: artifactacto
        uses: actions/upload-artifact@v4.6.2
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: .
